# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    parameters:
      string_to_print:
        type: string
        default: hello yogi
    steps:
      - run: echo << parameters.string_to_print >>

  error_handler:
    steps:
      - run: echo ERROR OCCURED!!!!!!

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: hello world
          command: echo "world"

  print_myname:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: myname
          command: echo $MY_NAME
      - print_pipeline_id:
          string_to_print: $CIRCLE_WORKFLOW_I
      - error_handler:
          when: on_fail



# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires: [print_hello]
      - print_myname

      